
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS'
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS'
export const REQUEST_POST = 'REQUEST_POST'
export const SET_AUTH_USER = 'SET_AUTH_USER'
export const RESET_AUTH_STATE = 'RESET_AUTH_STATE'
export const FETCH_USER_POSTS_SUCCESS = 'FETCH_USER_POSTS_SUCCESS'